name: Terraform EKS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check AWS identity
        run: aws sts get-caller-identity
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/resources/eks_cluster

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra/resources/eks_cluster

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra/resources/eks_cluster

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra/resources/eks_cluster
